import {
	DEFAULT_ACCOUNT_ID,
	type Persisted,
	type PlannedTransaction,
} from '../dataModel';

export const transaction1: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 0,
	name: 'Rent',
	categoryId: 0,
	type: 'expense',
	amount: 100,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('12-20-2025'),
	endDate: undefined,
};
export const transaction2: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 1,
	name: 'food',
	categoryId: 1,
	type: 'expense',
	amount: 40,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('2-21-2025'),
	endDate: undefined,
};
export const transaction3: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 2,
	name: 'Day trading',
	categoryId: 2,
	type: 'income',
	amount: 60,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('4-4-2025'),
	endDate: undefined,
};
export const transaction4: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 4,
	name: 'Train ticket',
	categoryId: 3,
	type: 'expense',
	amount: 3,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('3-12-2025'),
	endDate: undefined,
};
export const transaction5: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 5,
	name: 'Saving deposit',
	categoryId: 4,
	type: 'expense',
	amount: 80,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('8-20-2025'),
	endDate: undefined,
};

// transactions below are AI GENERATED

export const transaction6: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 6,
	name: 'Electricity bill',
	categoryId: 5,
	type: 'expense',
	amount: 45,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('01-15-2025'),
	endDate: undefined,
};
export const transaction7: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 7,
	name: 'Water bill',
	categoryId: 5,
	type: 'expense',
	amount: 25,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('01-18-2025'),
	endDate: undefined,
};
export const transaction8: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 8,
	name: 'Phone plan',
	categoryId: 5,
	type: 'expense',
	amount: 30,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-03-2025'),
	endDate: undefined,
};
export const transaction9: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 9,
	name: 'Internet',
	categoryId: 5,
	type: 'expense',
	amount: 55,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('03-02-2025'),
	endDate: undefined,
};
export const transaction10: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 10,
	name: 'Gym membership',
	categoryId: 6,
	type: 'expense',
	amount: 20,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-11-2025'),
	endDate: undefined,
};
export const transaction11: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 11,
	name: 'Freelance design',
	categoryId: 7,
	type: 'income',
	amount: 120,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-05-2025'),
	endDate: undefined,
};
export const transaction12: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 12,
	name: 'Streaming service',
	categoryId: 8,
	type: 'expense',
	amount: 10,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-17-2025'),
	endDate: undefined,
};
export const transaction13: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 13,
	name: 'Book purchase',
	categoryId: 9,
	type: 'expense',
	amount: 15,
	recurrenceInterval: 1,
	startDate: new Date('04-10-2025'),
	endDate: undefined,
};
export const transaction14: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 14,
	name: 'Ride share',
	categoryId: 3,
	type: 'expense',
	amount: 12,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('05-01-2025'),
	endDate: undefined,
};
export const transaction15: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 15,
	name: 'Interest income',
	categoryId: 4,
	type: 'income',
	amount: 5,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('05-05-2025'),
	endDate: undefined,
};
export const transaction16: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 16,
	name: 'Work lunch',
	categoryId: 11,
	type: 'expense',
	amount: 9,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('03-20-2025'),
	endDate: undefined,
};
export const transaction17: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 17,
	name: 'Coffee',
	categoryId: 11,
	type: 'expense',
	amount: 4,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('03-14-2025'),
	endDate: undefined,
};
export const transaction18: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 18,
	name: 'Parking',
	categoryId: 3,
	type: 'expense',
	amount: 6,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('04-11-2025'),
	endDate: undefined,
};
export const transaction19: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 19,
	name: 'Weekend market',
	categoryId: 1,
	type: 'expense',
	amount: 22,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('02-28-2025'),
	endDate: undefined,
};
export const transaction20: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 20,
	name: 'Dividends',
	categoryId: 10,
	type: 'income',
	amount: 40,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('06-07-2025'),
	endDate: undefined,
};
export const transaction21: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 21,
	name: 'Bike maintenance',
	categoryId: 3,
	type: 'expense',
	amount: 18,
	recurrenceInterval: 1,
	startDate: new Date('06-22-2025'),
	endDate: undefined,
};
export const transaction22: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 22,
	name: 'Garden supplies',
	categoryId: 2,
	type: 'expense',
	amount: 14,
	recurrenceInterval: 1,
	startDate: new Date('04-29-2025'),
	endDate: undefined,
};
export const transaction23: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 23,
	name: 'Web dev gig',
	categoryId: 7,
	type: 'income',
	amount: 200,
	recurrenceInterval: 1,
	startDate: new Date('05-16-2025'),
	endDate: undefined,
};
export const transaction24: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 24,
	name: 'Car fuel',
	categoryId: 3,
	type: 'expense',
	amount: 35,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('05-12-2025'),
	endDate: undefined,
};
export const transaction25: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 25,
	name: 'Laundry',
	categoryId: 0,
	type: 'expense',
	amount: 8,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-01-2025'),
	endDate: undefined,
};
export const transaction26: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 26,
	name: 'Coding course',
	categoryId: 9,
	type: 'expense',
	amount: 90,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('04-18-2025'),
	endDate: undefined,
};
export const transaction27: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 27,
	name: 'Craft sale',
	categoryId: 2,
	type: 'income',
	amount: 50,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('05-25-2025'),
	endDate: undefined,
};
export const transaction28: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 28,
	name: 'Snacks',
	categoryId: 11,
	type: 'expense',
	amount: 6,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('04-02-2025'),
	endDate: undefined,
};
export const transaction29: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 29,
	name: 'Pet food',
	categoryId: 12,
	type: 'expense',
	amount: 18,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-26-2025'),
	endDate: undefined,
};
export const transaction30: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 30,
	name: 'Dog walking',
	categoryId: 12,
	type: 'income',
	amount: 25,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-19-2025'),
	endDate: undefined,
};
export const transaction31: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 31,
	name: 'Laundry detergent',
	categoryId: 0,
	type: 'expense',
	amount: 7,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('03-07-2025'),
	endDate: undefined,
};
export const transaction32: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 32,
	name: 'Medicine',
	categoryId: 6,
	type: 'expense',
	amount: 12,
	recurrenceInterval: 1,
	startDate: new Date('04-13-2025'),
	endDate: undefined,
};
export const transaction33: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 33,
	name: 'Car wash',
	categoryId: 3,
	type: 'expense',
	amount: 10,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('04-21-2025'),
	endDate: undefined,
};
export const transaction34: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 34,
	name: 'YouTube revenue',
	categoryId: 2,
	type: 'income',
	amount: 75,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('06-01-2025'),
	endDate: undefined,
};
export const transaction35: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 35,
	name: 'Haircut',
	categoryId: 0,
	type: 'expense',
	amount: 15,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-09-2025'),
	endDate: undefined,
};
export const transaction36: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 36,
	name: 'Makeup products',
	categoryId: 0,
	type: 'expense',
	amount: 20,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('03-22-2025'),
	endDate: undefined,
};
export const transaction37: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 37,
	name: 'Recycling deposit return',
	categoryId: 0,
	type: 'income',
	amount: 8,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('05-19-2025'),
	endDate: undefined,
};
export const transaction38: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 38,
	name: 'Garden veggies sale',
	categoryId: 2,
	type: 'income',
	amount: 30,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('06-12-2025'),
	endDate: undefined,
};
export const transaction39: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 39,
	name: 'Music subscription',
	categoryId: 8,
	type: 'expense',
	amount: 12,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('01-25-2025'),
	endDate: undefined,
};
export const transaction40: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 40,
	name: 'Cloud storage',
	categoryId: 5,
	type: 'expense',
	amount: 5,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-14-2025'),
	endDate: undefined,
};
export const transaction41: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 41,
	name: 'Dance class',
	categoryId: 2,
	type: 'expense',
	amount: 25,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('04-05-2025'),
	endDate: undefined,
};
export const transaction42: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 42,
	name: 'Teaching tutoring',
	categoryId: 7,
	type: 'income',
	amount: 60,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-30-2025'),
	endDate: undefined,
};
export const transaction43: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 43,
	name: 'Ski pass',
	categoryId: 2,
	type: 'expense',
	amount: 40,
	recurrenceInterval: 1,
	startDate: new Date('01-20-2025'),
	endDate: undefined,
};
export const transaction44: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 44,
	name: 'Ice cream',
	categoryId: 11,
	type: 'expense',
	amount: 5,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('06-15-2025'),
	endDate: undefined,
};
export const transaction45: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 45,
	name: 'Train subscription',
	categoryId: 3,
	type: 'expense',
	amount: 60,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-02-2025'),
	endDate: undefined,
};
export const transaction46: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 46,
	name: 'Cooking class',
	categoryId: 9,
	type: 'expense',
	amount: 35,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('04-16-2025'),
	endDate: undefined,
};
export const transaction47: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 47,
	name: 'Meal prep side gig',
	categoryId: 7,
	type: 'income',
	amount: 45,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('05-03-2025'),
	endDate: undefined,
};
export const transaction48: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 48,
	name: 'Home cleaning',
	categoryId: 0,
	type: 'expense',
	amount: 20,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-17-2025'),
	endDate: undefined,
};
export const transaction49: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 49,
	name: 'Plant sale',
	categoryId: 2,
	type: 'income',
	amount: 18,
	recurrenceInterval: 1,
	startDate: new Date('05-29-2025'),
	endDate: undefined,
};
export const transaction50: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 50,
	name: 'Smoothie',
	categoryId: 11,
	type: 'expense',
	amount: 6,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('04-09-2025'),
	endDate: undefined,
};
export const transaction51: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 51,
	name: 'Cat toys',
	categoryId: 12,
	type: 'expense',
	amount: 7,
	recurrenceInterval: 1,
	startDate: new Date('03-06-2025'),
	endDate: undefined,
};
export const transaction52: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 52,
	name: 'Cat sitting',
	categoryId: 12,
	type: 'income',
	amount: 22,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-27-2025'),
	endDate: undefined,
};
export const transaction53: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 53,
	name: 'Home decor',
	categoryId: 0,
	type: 'expense',
	amount: 28,
	recurrenceInterval: 1,
	startDate: new Date('02-19-2025'),
	endDate: undefined,
};
export const transaction54: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 54,
	name: 'Printer ink',
	categoryId: 7,
	type: 'expense',
	amount: 14,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('05-09-2025'),
	endDate: undefined,
};
export const transaction55: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 55,
	name: 'Calligraphy commission',
	categoryId: 2,
	type: 'income',
	amount: 40,
	recurrenceInterval: 1,
	startDate: new Date('04-28-2025'),
	endDate: undefined,
};
export const transaction56: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 56,
	name: 'Board game',
	categoryId: 8,
	type: 'expense',
	amount: 18,
	recurrenceInterval: 1,
	startDate: new Date('06-04-2025'),
	endDate: undefined,
};
export const transaction57: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 57,
	name: 'Language tutoring',
	categoryId: 9,
	type: 'income',
	amount: 50,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('03-23-2025'),
	endDate: undefined,
};
export const transaction58: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 58,
	name: 'Festival ticket',
	categoryId: 8,
	type: 'expense',
	amount: 65,
	recurrenceInterval: 1,
	startDate: new Date('07-14-2025'),
	endDate: undefined,
};
export const transaction59: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 59,
	name: 'Cleaning supplies',
	categoryId: 0,
	type: 'expense',
	amount: 11,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('02-27-2025'),
	endDate: undefined,
};
export const transaction60: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 60,
	name: 'Chocolate',
	categoryId: 11,
	type: 'expense',
	amount: 3,
	recurrenceInterval: 1,
	recurrenceBase: 'day',
	startDate: new Date('01-30-2025'),
	endDate: undefined,
};
export const transaction61: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 61,
	name: 'Phone repair',
	categoryId: 5,
	type: 'expense',
	amount: 50,
	recurrenceInterval: 1,
	startDate: new Date('03-10-2025'),
	endDate: undefined,
};
export const transaction62: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 62,
	name: 'Fruit stand sale',
	categoryId: 11,
	type: 'income',
	amount: 14,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('04-14-2025'),
	endDate: undefined,
};
export const transaction63: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 63,
	name: 'Local charity donation',
	categoryId: 0,
	type: 'expense',
	amount: 10,
	recurrenceInterval: 1,
	recurrenceBase: 'month',
	startDate: new Date('05-13-2025'),
	endDate: undefined,
};
export const transaction64: Persisted<PlannedTransaction> = {
	accountId: DEFAULT_ACCOUNT_ID,
	id: 64,
	name: 'Mandolin lesson',
	categoryId: 2,
	type: 'income',
	amount: 32,
	recurrenceInterval: 1,
	recurrenceBase: 'week',
	startDate: new Date('06-19-2025'),
	endDate: undefined,
};
export const test_transactions: Persisted<PlannedTransaction>[] = [
	transaction1,
	transaction2,
	transaction3,
	transaction4,
	transaction5,
	transaction6,
	transaction7,
	transaction8,
	transaction9,
	transaction10,
	transaction11,
	transaction12,
	transaction13,
	transaction14,
	transaction15,
	transaction16,
	transaction17,
	transaction18,
	transaction19,
	transaction20,
	transaction21,
	transaction22,
	transaction23,
	transaction24,
	transaction25,
	transaction26,
	transaction27,
	transaction28,
	transaction29,
	transaction30,
	transaction31,
	transaction32,
	transaction33,
	transaction34,
	transaction35,
	transaction36,
	transaction37,
	transaction38,
	transaction39,
	transaction40,
	transaction41,
	transaction42,
	transaction43,
	transaction44,
	transaction45,
	transaction46,
	transaction47,
	transaction48,
	transaction49,
	transaction50,
	transaction51,
	transaction52,
	transaction53,
	transaction54,
	transaction55,
	transaction56,
	transaction57,
	transaction58,
	transaction59,
	transaction60,
	transaction61,
	transaction62,
	transaction63,
	transaction64,
];

export const test_category_names = [
	'Living',
	'Groceries',
	'Hobbies & Side Income',
	'Transportation',
	'Savings',
	'Utilities',
	'Health & Fitness',
	'Freelance & Work',
	'Entertainment',
	'Education',
	'Investments',
	'Dining & Snacks',
	'Pets',
];
